print("Hello world")
a= float(input("your first number:"))
b= float(input("your second number:"))
print("if we multiply, we get: ", a*b)
print("Add: ", a+b)
print("Division of first numb by second numb is ", a/b)
